WORD_PAIRS = [
    ("baseball", "softball"),
    ("detective", "spy"),
    ("zombie", "ghost"),
    ("cathedral", "monastery"),
    ("passport", "visa"),
    ("sofa", "beanbag"),
    ("orchard", "vineyard"),
    ("contact lens", "glasses"),
    ("lemon", "grapefruit"),
    ("port", "canal"),
    ("microscope", "endoscope"),
    ("orchestra", "choir"),
    ("pancake", "waffle"),
    ("muffin", "scone"),
    ("camel", "llama"),
    ("jelly", "pudding"),   
    ("Italy", "France"),
    ("rugby", "American football"),
    ("bouldering", "rock climbing"),
    ("virus", "bacteria"),
    ("coffee", "espresso"),
    ("latte", "cappuccino"),
    ("Sunday", "public holiday")
]
